### ISSUE TITLE
The transition animation doesn't feel right

### ISSUE THREAD

**Issue by arovillard** [troch/angular-multi-step-form#12]
When you move from one step to the other, the `old step` gets dropped to the bottom instead of sliding to the left as the `new step` slides in.

Is this a bug?

**Comment by troch** [comment]
On the example page?

**Comment by arovillard** [comment]
yes, http://blog.reactandbethankful.com/angular-multi-step-form/#/css-transitions

When you navigate to the next step, it abruptly drops the current step and then makes the sliding effect of both steps.

**Comment by troch** [comment]
It is just a CSS issue I never fixed. Not related to the library itself.

**Comment by arovillard** [comment]
Are you planning on fixing it anytime soon?

**Comment by troch** [comment]
I should, but once again it is not related to the library itself.
Animations are CSS transitions.

**Comment by troch** [comment]
Styles have been fixed, and transitions are now showing fine :tada:
