### ISSUE TITLE
Add more steps dynamically?

### ISSUE THREAD

**Issue by quangdng** [troch/angular-multi-step-form#14]
I could not find a way to add more steps dynamically. I presume that we inject the multiStepFormInstance to get steps array and add more steps using that array. However, angular returns me injection error when I try to inject multiStepFormInstance to my controller.

Thanks for your support.

Regards.

**Comment by troch** [comment]
When you say _my controller_, what controller are you refering to? As it stands, `multiStepFormInstance` can only be injected in step controllers. From `multiStepContainer` scope, you have access to `$getSteps()`.

Adding steps dynamically is a tricky business, I recommend only trying to add steps after your currently active step. Best way might be to have all your steps configured but only being able to activate a few. One way I have dealt with it myself in the past is to add a data boolean per step (i.e. isVisible) and only displaying them in my header + adding a bit of logic to prev and next buttons.

**Comment by troch** [comment]
Anyway, there are a few ways I can make it easier. Let me know your thoughts.

**Comment by quangdng** [comment]
Thanks for your quick reply. I've managed to add steps dynamically through $getSteps() API.

You are right, I inject multiStepFormInstance in multiStepContainer scope. That's why I got error. Anyway, really appreciate your helpful response.

**Comment by troch** [comment]
No problem. I could have a `getMultiStepFormInstance` method on `multiStepContainer` directive controller. So if you want to place a custom directive in `multiStepContainer`, you could use `require: ^^multiStepContainer` and get access to `multiStepFormInstance`. Would that help?

**Comment by quangdng** [comment]
That's incredible.

However, I found most of my business logic needs could be achieved with your provided APIs. Excellent work!

**Comment by troch** [comment]
:+1: Closing this issue then
