### ISSUE TITLE
Programatically move to next step

### ISSUE THREAD

**Issue by edhollinghurst** [troch/angular-multi-step-form#16]
Hi

Great project!

I was just wondering if you were able to provide an example of how to programatically move to the next step?

I'm trying to achieve something like this:

``` html
<button ng-click="submit()">Submit</button>
```

``` javascript
$scope.submit = function() {
  MyService.postData()
    .then(function() {
      // Go to next form step
    })
  ;
};
```

Many thanks!

**Comment by troch** [comment]
What is `$scope` in your example? Are you inside a step controller?

**Comment by edhollinghurst** [comment]
Yes inside a controller with isolated scope.

**Comment by troch** [comment]
If you are inside a step controller, `$sccope` is augmented with control flow functions (isolated or not), as documented here: https://github.com/troch/angular-multi-step-form/blob/master/docs/scopes.md. So you can perform `$scope.$nextStep()` to go to your next step.

Alternatively (especially for `controllerAs` syntax when you don't want to inject `$scope`), you can inject `multiStepFormInstance` and call `multiStepFormInstance.nextStep()` or other API methods: https://github.com/troch/angular-multi-step-form/blob/master/docs/multi-step-instance.md.

**Comment by edhollinghurst** [comment]
That's great - thanks !
