### ISSUE TITLE
Animation & Search-ID

### ISSUE THREAD

**Issue by cmarin** [troch/angular-multi-step-form#19]
Thank you for sharing a such a useful library!  I was curious if you had any ideas around using the transition animations in conjunction with the step URL parameter.  I can get either to work separately, but once I add that search-id setting then the transition animations disappear.

**Comment by troch** [comment]
Thanks for raising this, definitely a bug. I don't have much time until end of the year, but I'll fix it as soon as I can.

**Comment by cmarin** [comment]
Much appreciated!

**Comment by troch** [comment]
@cmarin It turns out it is actually not a bug. What happens is that your view might be reloaded. When using ngRoute, you need to configure your views with `reloadOnSearch: false`. Same for ui-router.

**Comment by cmarin** [comment]
Much appreciated. Happy new year!

**Comment by troch** [comment]
Happy new year to you too! :smile:
