### ISSUE TITLE
Support both a header and a footer

### ISSUE THREAD

**Issue by tinusn** [troch/angular-multi-step-form#2]
This would make the component more flexible.

As an example, see:
https://material.angularjs.org/latest/#/api/material.components.gridList/directive/mdGridTile
and
https://material.angularjs.org/latest/#/api/material.components.card/directive/mdCard

```
<multi-step-container>
    <multi-step-header>
    </multi-step-header>
    <multi-step-content>
    </multi-step-content>
    <multi-step-footer>
    </multi-step-footer>
</multi-step-container>
```

or simply

```
<multi-step-container>
    <p>content</p>
    <multi-step-footer>
    </multi-step-footer>
</multi-step-container>
```

**Comment by troch** [comment]
Good idea. I'll look into it after the controllerAs syntax. I'll probably end up needing to bump the minor version as it will be a breaking change.

**Comment by troch** [comment]
No transclusion any more and full control of your markup. Note that both directives (multiStepContainer and stepContainer) can be used as elements or attributes.

``` html
<multi-step-container steps="steps">
   <!-- wathever you want before... -->

    <step-container></step-container>

    <!-- ... and after, as long as step-container is defined somewhere -->
</multi-step-container>
```
