### ISSUE TITLE
explanation about $dismiss()

### ISSUE THREAD

**Issue by joelmuskwe** [troch/angular-multi-step-form#21]
Hi i was implementing the inside a modal example though for the modal i was using materialize modal. everything seems to be working fine except on the implementation of the cancel button. issue is when i open up the modal again it shows the last step before i closed it. The previous step also stopped working and remains on the final step.

**Comment by troch** [comment]
`$dismiss` comes from https://angular-ui.github.io/bootstrap/, for material dialog you need to add `$mdDialog.hide` to your modal scope.

**Comment by troch** [comment]
Normally, a modal should be instanciated fully when shown (not once, and then shown again). Check that is the case. Also what you can do is explicitly pass an initial step.
