### ISSUE TITLE
Still facing challenges with angular-multi-step-form and materialize modal

### ISSUE THREAD

**Issue by joelmuskwe** [troch/angular-multi-step-form#22]
Can you please share with me how i can explicitly initialize angular-multi-step-form to the first step when i open the modal

**Comment by troch** [comment]
Sorry I don't know what materialize modal is, I thought you meant material modal.

**Comment by joelmuskwe** [comment]
It's basically a modern responsive front-end framework based on Material Design http://materializecss.com/

**Comment by troch** [comment]
I'm sorry but I cannot help.
