### ISSUE TITLE
Uncaught ReferenceError: exports is not defined

### ISSUE THREAD

**Issue by davidmir** [troch/angular-multi-step-form#24]
Hi,

Why I'm getting this error? How I setup the angular-multi-step-form on may AngularJS App?

Thanks

**Comment by troch** [comment]
What source file are you trying to use? Are you using CommonJS modules / ES6 modules / globals? What are you using for compiling / bundling your code?

**Comment by davidmir** [comment]
Sorry, I solve that by using angular-multi-step-form.min.js.
