### ISSUE TITLE
Possible to have a full working example ?

### ISSUE THREAD

**Issue by jdriesen** [troch/angular-multi-step-form#29]
Hi Sir,
Congratz with the development of this component. I a newbie related to Angular, and I tried to make your component working, but I can't succeed.

Can I ask you to give me more details about the index.html and the JS file I have to use ?
(more specific, please tell me which scripts I've to include, and I hope you can give me an example of the angular file as well...

Thanks in advance !
Kind regards,

Johnny Driesen

**Comment by troch** [comment]
Hi Johnny,

If you are starting with Angular, unfortunately for you this angular component is not destined to teach how to write applications with Angular. There are plenty of resources on-line which will help your learning journey.
- For the sources, I have a "Getting started" (with this library, not angular): https://github.com/troch/angular-multi-step-form#getting-started. I recommend you use a package manager (npm or bower). What you are after is probably the browser distribution, located in `dist/browser': https://github.com/troch/angular-multi-step-form/tree/master/dist/browser
- I have documentation: https://github.com/troch/angular-multi-step-form#docs
- I have examples: https://github.com/troch/angular-multi-step-form#examples

The examples I have are pretty basic and designed to showcase the capabilities of the library, but they are fully working.

**Comment by jdriesen** [comment]
Thanks for your quick & extended reply, Troch.
You're examples are really extended, but it seems I'm missing 'the picture' somewhere - somehow ...

e.g. at http://blog.reactandbethankful.com/angular-multi-step-form/#/using-forms I see 'parts' of a script and 'parts' of the HTML file ... and that causes me some probs...

But I hope I can manage it.

PS.: I'm not - yet - used to work with packet-managers... (is also an item on my 'to learn' list...) 
Most of the time, I'm downloading the ZIP file ...

Kind regards,
Johnny

**Comment by troch** [comment]
As you said, they are 'parts'. HTML parts are angular partials, JS scripts are usually parts of controllers. More knowledge of Angular will help you making sense of those.

**Comment by jdriesen** [comment]
OK. Thanks. Gonna try to improve my Angular knowledge asap and maybe coming back to this later on.

Grtz,
Johnny

**Comment by troch** [comment]
OK, closing for now
