### ISSUE TITLE
Get validation of forms in different steps

### ISSUE THREAD

**Issue by gustavogsimas** [troch/angular-multi-step-form#32]
Ok, here's the deal, im not being able to see if the forms in the other steps are valid or not.

For example, i'm in the first step and i wanna see if all the other step's forms are valid without going to those steps. 

I tried to envolve the whole multi-step-container in only one form, didnt work.
I tried to use the $getSteps function, it indeed returned all the steps, but returned the valid attribute false for all of them, even if some of them are correctly valid. 

Is this possible or i have to create a custom directive to do this? Thanks in advance.

**Comment by troch** [comment]
What have you tried to check if steps are valid or not?

**Comment by gustavogsimas** [comment]
I wasn't checking, the user was able to navigate through steps without validating them. And then when he clicked the save button, i wanted to check all the forms. 

Anyway I got it working making changes in my background, Sorry for my bad English and Thanks for your attention =)
