### ISSUE TITLE
Get title of next step

### ISSUE THREAD

**Issue by remib** [troch/angular-multi-step-form#33]
This module is really useful, thanks.

I'm just struggling to get the title of the next and previous steps in a similar way as you do for the active step i.e. $getSteps().title

Is there a simple way?

Thanks again

**Comment by troch** [comment]
https://github.com/troch/angular-multi-step-form/blob/master/docs/multi-step-instance.md

You can use
- getSteps
- isFirst, isLast
- getActiveIndex

To do something like this:

``` js
const prevTitle = $scope.$isFirst() ? null : $scope.$getSteps()[$scope.$getActiveIndex() - 1].title;
const nextTitle = $scope.$isLast() ? null : $scope.$getSteps()[$scope.$getActiveIndex() + 1].title;
```

**Comment by remib** [comment]
Edit: Please ignore, I'm being incredibly stupid. The page is called type. I am an idiot. Thanks a lot!
