### ISSUE TITLE
Next and previous titles not working as intended

### ISSUE THREAD

**Issue by remib** [troch/angular-multi-step-form#34]
Sorry to reopen this but after much experimentation I'm still not achieving the desired outcome.

I am using the following code for next and previous buttons to show the title of the respective pages alongside the button:

`<strong ng-bind-template="{{$isFirst() ? null : $getSteps()[$getActiveIndex() - 1].title}}"></strong>`

`<strong ng-bind-template="{{$isLast() ? null : $getSteps()[$getActiveIndex() + 1].title}}"></strong>`

However this does not have the desired outcome. I have created an example array of steps whose titles are numbers from 1-6 to see what is going on.

When the page initially loads I see:
Next: 3 (where this should be 2)

Then as I click next through the steps I see:
Previous: 2, Next: 4 (should be 1,3)
Previous: 3, Next: 5 (should be 2, 4)
Previous: 4, Next:6 (should be 3, 5)
Previous: 5, Next: blank/null (should be 4, 6)
Previous: 6, Next: null (should be 5, null)

**Comment by troch** [comment]
Yep, sorry about that. Steps indexes starts at 1.

``` html
<strong ng-bind-template="{{$isFirst() ? null : $getSteps()[$getActiveIndex() - 2].title}}"></strong>

<strong ng-bind-template="{{$isLast() ? null : $getSteps()[$getActiveIndex()].title}}"></strong>
```

**Comment by remib** [comment]
Of course! It's late and my brain isn't working, time to stop! Thanks a lot.
