### ISSUE TITLE
Steps Controller Not working

### ISSUE THREAD

**Issue by sajumani** [troch/angular-multi-step-form#37]
Hi,

Each steps, controller not working ( Am setting $rootScope value from the ctrl ,its not functionalable)

app.controller('Step1Ctrl', function ($scope, multiStepFormInstance,$rootScope) {
									   $rootScope.isJoinStep = false;
});

**Comment by troch** [comment]
What is not working?

**Comment by sajumani** [comment]
Sorry, the problem was, i had created multiple Ctrl with same name
