### ISSUE TITLE
There is no css file?

### ISSUE THREAD

**Issue by arnaugm** [troch/angular-multi-step-form#40]
I can't find the stylesheet file for the classes used in the examples.

**Comment by troch** [comment]
https://github.com/troch/troch.github.io/tree/master/angular-multi-step-form

**Comment by arnaugm** [comment]
Why they are not in the same repo? it would be handy.

**Comment by troch** [comment]
Handy for what? they are illustrative examples of a JS library, and the CSS for them is located where they are hosted.

Now, if you wanted to do a copy paste and raised an **issue** because you couldn't, then I'm GLAD to have made it awkward for you. Bye.

**Comment by arnaugm** [comment]
I just thought examples where part of the library and stylesheets were missing. Now I see your point. Don't need to be rude man ;)

**Comment by troch** [comment]
The reason for being rude is your rudeness in the first place. Being polite when asking for something goes a long way.
