### ISSUE TITLE
Finish called on destroy instead of cancel

### ISSUE THREAD

**Issue by rdzidziguri** [troch/angular-multi-step-form#41]
I have a multystep container within another directive which works perfectly till i try to destroy parent container. when parent container is destroyed, instead of calling cancel it calls onFinish which makes it usless because every time i try to close drawer onFinish is called which results in API call. is that normal should not finish be called explicitly? why is it always calling finish even if parent container gets destroyed without finishing wizard?

**Comment by troch** [comment]
No it's not normal, and that is a bug, fixed in 1.2.9
