### ISSUE TITLE
Using ControllerAs for child scope controllers

### ISSUE THREAD

**Issue by rdzidziguri** [troch/angular-multi-step-form#42]
Is it possible to have a controller which does not take $scope but use ControllerAs feature so that istead of using 
`function someController($scope, multiStepFormScope) {
        $scope.somedata = 'value';
    }`

i could use
`function someController(multiStepFormScope) {
        var vm = this;
        vm.somedata = 'value';
    }`

and inside step HTML i could refer to it in the following way.

`<input type="number" style="display: none" ng-model="vm.contactList.length" min="1" required />`

**Comment by troch** [comment]
As specified in the docs: https://github.com/troch/angular-multi-step-form/blob/master/docs/configuring-steps.md
