### ISSUE TITLE
How can I intercept correctly the next event on each step?

### ISSUE THREAD

**Issue by empav** [troch/angular-multi-step-form#46]
Hi there, how can I intercept correctly the next event on each step? I see there's onStepChange() callback but I can't get how it works. Should I provide an onStepChange function in-scope for each controller involved in the multistep form?

**Comment by troch** [comment]
`onStepChange` is on the directive itself, it is an external function you can pass to the directive so it gets called back on each step change. It is not on the scope of the directive or its steps.

**Comment by empav** [comment]
All right ok. Can you give me a smart way to intercept programmatically "next" and "previous" event on each step?

**Comment by troch** [comment]
You can try to decorate the `nextStep` and `prevStep` methods of `multiStepFormInstance`.

**Comment by empav** [comment]
Would you point me to the right direction to do that? Or make me an example...thanks.

**Comment by troch** [comment]
> Would you point me to the right direction to do that?

https://www.google.co.uk/#q=javascript+decorator+pattern

> Or make me an example

I hope you are joking...
