### ISSUE TITLE
Going to previous step resets form validity to false

### ISSUE THREAD

**Issue by crypticcookee** [troch/angular-multi-step-form#47]
Hi,

I have a form in a step which performs calculations. Based on the calculations I use $scope.$setValidity() function to set it to true or false. This works fine for the next button. But when I click on previous it resets the validity. I have tried to rerun the script on page load but it it seems the values set in the script are ignored. Is there a way to preserve the validity of previous form?

Thanks

**Comment by troch** [comment]
`setValidity` isn't called anywhere in the library itself, you might be resetting it yourself by accident? It is also called by `form-step-validity` directive (if you use it) and the validity value would be the one from your angular form.

**Comment by crypticcookee** [comment]
Thanks, figured it out, the form element had the form-step-validity
directive which
was causing the issue.

Regards
