### ISSUE TITLE
Is it possible to disable and enable a step from controller ?

### ISSUE THREAD

**Issue by LearnGrowAndShare** [troch/angular-multi-step-form#48]
Hi, 

Lets say we have 4 steps, and want only one step to be enable at a time, so is there any method exposed to acheive it  ?
Is it possible to disable and enable a step from Controller ?

**Comment by troch** [comment]
You can, but you have to take care of it yourself (by calling `$setActiveIndex()` rather than `$nextStep()`, only exposing valid controls to your users)
