### ISSUE TITLE
Support nav pills

### ISSUE THREAD

**Issue by joerno** [troch/angular-multi-step-form#5]
Hello,

would be nice to have the steps on top like here: http://www.bootply.com/sethfam/Ol5FB9IfJF (next to the navigation buttons like it is)

regards

**Comment by troch** [comment]
Hi @joerno, you can do that no problem. You are fully in control of the markup you use for your steps and for what you put before and after your step container. So there is nothing stopping you re-using the same markup and stylesheet used in that example.

**Comment by joerno** [comment]
Hi Thomas, thanks a lot for your answer. Do you have an example, how to add the steps and make them clickable to switch between them?

**Comment by troch** [comment]
You configure your steps like you would configure your views using ngRoute or ui-router: you specify a template, a controller, etc...: https://github.com/troch/angular-multi-step-form/blob/master/docs/configuring-steps.md

You need to use two provided directive: `multiStepContainer` and `stepContainer`. `stepContainer` has to be inside `multiStepContainer` and you can add a footer and/or header around it no problem (see examples on website).

``` html
<multi-step-container steps="yourSteps">
    <!-- Here your list of steps -->
    <step-container></step-container>
</multi-step-container>
```

When you create a multi step form, an _instance_ is created. This instance has several methods (https://github.com/troch/angular-multi-step-form/blob/master/docs/multi-step-instance.md) that you can access two ways:
- By injecting `multiStepFormInstance` in your step controllers
- Scopes (multi step container scope and step scope) are augmented with several methods with a $: https://github.com/troch/angular-multi-step-form/blob/master/docs/scopes.md
