### ISSUE TITLE
Is there any demo?

### ISSUE THREAD

**Issue by JFC-MC** [troch/angular-multi-step-form#54]
Hello,

Would you be so kind to share some demo(examples) to show us how it looks.
Sorry, but I didn't find any examples(I mean ready to use multi-steps wizards) built on top of this project.

Thanks!

**Comment by troch** [comment]
You mean http://blog.reactandbethankful.com/angular-multi-step-form?

**Comment by JFC-MC** [comment]
Thanks for rapid answer.

Actually I meant something like this:
https://github.com/amoffat/bootstrap-application-wizard
(they don't have a decent  screenshots however they have VERY good working example in demo directory inside, where you can see this wizard in the REAL action, not just some steps)

**Comment by troch** [comment]
Unfortunately I don't have the time to develop complex, more real examples.The examples I provide are designed to give an overview of the library capabilities.
