### ISSUE TITLE
Angular Can't inject multiStepFormInstance 

### ISSUE THREAD

**Issue by ricardoborges** [troch/angular-multi-step-form#56]
Hey guys,
Everything is working fine in my app with multistepform, but when I try to put the multiStepFormInstance reference on controller, the injector throws an error.

Error: $injector:unprUnknown Provider
Unknown provider: multiStepFormInstanceProvider <- multiStepFormInstance <- FormController

Am I missing something?

**Comment by troch** [comment]
Where and how are you using `FormController`?

**Comment by ricardoborges** [comment]
Hi, sorry about the delay! 

It's a single controller app, the same tag I define app and controller. 

<div ng-app="formApp" ng-controller="FormController" class="ng-cloak" ng-init='setup("Pesquisa")'>

it works:

angular.module('formApp', ['multiStepForm', 'checklist-model', 'angular-ladda', 'lr.upload', 'ngAnimate', 'toastr', 'ngValidate'])
            .controller('FormController', ['$scope', '$http', '$window', 'toastr', 'toastrConfig',
                function ($scope, $http, $window, toastr, toastrConfig) {

but I can't inject multiStepFormInstance in this controller

**Comment by ricardoborges** [comment]
<div ng-app="formApp" ng-controller="FormController" class="ng-cloak" ng-init='setup("Pesquisa")'>

**Comment by ricardoborges** [comment]
`<div ng-app="formApp" ng-controller="FormController" class="ng-cloak" ng-init='setup("Pesquisa")'>`

**Comment by ricardoborges** [comment]
`        angular.module('formApp', ['multiStepForm', 'checklist-model', 'angular-ladda', 'lr.upload', 'ngAnimate', 'toastr', 'ngValidate'])
            .controller('FormController', ['$scope', '$http', '$window', 'toastr', 'toastrConfig',
                function ($scope, $http, $window, toastr, toastrConfig) {`

**Comment by troch** [comment]
You can only inject `multiStepFormInstance` in a step controller or in the multi step directive controller.
