### ISSUE TITLE
On Next button click validate the form 

### ISSUE THREAD

**Issue by madhuvuvaddi** [troch/angular-multi-step-form#58]
I have verified that here we are disabling next button until the form is valid but I want to validate and set the focus to first element of the step when user hit the next button is it possible with this library?
want to call this code on next step
if(!formCtrl.$valid){
                     element[0].querySelector('.ng-invalid').focus();  
                     var myEl = angular.element( element[0].querySelector('.ng-invalid') );
                     myEl.css('border','solid 1px red');

```
             }
```

**Comment by troch** [comment]
This has nothing to do with this library, within a step (partial + controller) you can do whatever you want.

**Comment by madhuvuvaddi** [comment]
Thanks for your quick response.Where exactly I need to put this code nextstep()?
Then how to get that element in nextStep().Could you please help me to resolve this.

**Comment by troch** [comment]
From a controller where you call $nextStep you can inject $element. I can't help further.
