### ISSUE TITLE
Please share code of examples?

### ISSUE THREAD

**Issue by dclarke83** [troch/angular-multi-step-form#59]
Please may you share the code of your examples from here: http://blog.reactandbethankful.com/angular-multi-step-form

Many other modules include the code of their examples in the same git, and it would be really helpful to those of us who are newer to Angular.

**Comment by troch** [comment]
The code you need to know about is on the page of each example. Files are here: https://github.com/troch/troch.github.io/tree/master/angular-multi-step-form.

If you need more Angular examples, for education purposes, this is not the place. There are plenty of learning online courses and resources available on the web.

**Comment by dclarke83** [comment]
Thank you - providing the code of the documentation helped me a lot.
