### ISSUE TITLE
Scroll to top on view change

### ISSUE THREAD

**Issue by JeanHules** [troch/angular-multi-step-form#6]
I have a 4 stage form, two of the sections are a little longer than the viewport height. So when a user scrolls down and clicks next, the next form stage is visible partially scrolled. Is it possible to scroll to the top of the form when the user clicks next? 

I love this directive, but that is the only thing I am not able to accomplish.

**Comment by troch** [comment]
Hi @JeanHules, that would be no problem. I'll have time to look at it tomorrow.

**Comment by troch** [comment]
`scrollTop` for the step container will be set to `0` on step transition. If it is another element you want to scroll, then I will need to add a new callback `onTransition`.

**Comment by troch** [comment]
Version `1.2.0` released:
- Scroll to top of `<form-step-container>`
- You can provide an `onStepChange` callback if you need to do other DOM manipulations

**Comment by JeanHules** [comment]
This looks great. Thank you very much.
