### ISSUE TITLE
Controlling an angular-multi-step-form from a controller (changing step index)

### ISSUE THREAD

**Issue by thirionjwf** [troch/angular-multi-step-form#7]
Hi there,

I am trying to control a multi-step form from a controller. In my app a user logs in and then inside a tab view, a multi-step form is presented on one of the tabs. When user logs out with a button that is outside the multi-step-container directive, I am not able to change the step back to step 1 using $setActiveIndex(1). Hence the reason to want to change the step back to step 1 inside my logout function in the controller.

Is there a way to call $setActiveIndex(1) from inside my controller? I tried adding $multiStepForm and multiStepForm as dependencies in my controller, but when I try to use it, it is undefined. I see there is a factory, but can this be used inside a controller? I must be doing something wrong here.

Thanks in advance!

**Comment by thirionjwf** [comment]
Here is the relevant code snippets:

``` javascript
.controller('MyCtrl', function ($scope, $state, AuthService, $multiStepForm) {
    $scope.reset = function() {
        $scope.model = {};
    }

    $scope.logout = function () {
        $multiStepFormInstance.setActiveIndex(1);
        AuthService.logout();
        $state.go('login');
    };

   ....
})
```

``` html
<ion-view view-title="StepsTab" name="step-tabs-view">
    <ion-nav-buttons side="right">
        <button class="button icon ion-log-out button-stable" ng-click="logout()"></button>
    </ion-nav-buttons>

    <ion-content class="padding">
        <multi-step-container steps="steps">
            <header>
                <div id="status-buttons" class="text-center">
                    <a ng-class="$getActiveStep().title == 'Step1' ? 'active' : ''"><span>1</span> Step 1</a>
                    <a ng-class="$getActiveStep().title == 'Step2' ? 'active' : ''"><span>2</span> Step 2</a>
                    <a ng-class="$getActiveStep().title == 'Step3' ? 'active' : ''"><span>3</span> Step 3</a>
                </div>

                <div class="stepHeading">
                    {{$getActiveStep().title}}
                </div>

                <div style="{{$isLast() ? 'display: none' : ''}}">
                    <br>
                    <button ng-disabled="$isFirst()" class="button button-small button-stable ion-chevron-left" ng-click="$previousStep()">
                        Previous
                    </button>
                    <button ng-disabled="$isLast() || ($getActiveStep().hasForm && !$getActiveStep().valid)" class="button button-small button-stable icon-right ion-chevron-right" ng-click="$nextStep()">Next
                    </button>
                </div>

                <div style="{{$isLast() ? '' : 'display: none'}}">
                    <br>
                    <button class="button button-small button-stable" ng-click="reset(); $setActiveIndex(1)">Done
                    </button>
                </div>
            </header>

            <br>

            <main step-container></main>
        </multi-step-container>
    </ion-content>
</ion-view>
```

**Comment by troch** [comment]
Hi @thirionjwf,

You are not doing anything wrong. You cannot inject `multiStepInstance` outside the directive because it is not available application wide (it is specific to that instance).

Currently it is not possible to control a multiStepForm instance from outside the directive. I can work on a solution, however from an application perspective I would encourage you to destroy the multiStepForm instance and create a new one rather than trying to go back to step 1 (which is not a proper "reset").

You can simply destroy the directive by forcing a reload of your view. That would reset the multi-step form.

**Comment by thirionjwf** [comment]
Thank you. I assume you refer to something like:

$scope.reloadRoute = function() {
   $route.reload();
}

which will reload the current route. Or would the form instance only get destroyed on a full refresh, i.e.:

$scope.reloadRoute = function() {
   $window.location.reload();
}

Great plugin. Works very well.

**Comment by troch** [comment]
A route reload will be enough, no need to refresh / reload the page. Not sure how do to so with `<ion-view/>`. It might involve `$route` if based on ngRoute or `$state` if based on `ui-router`.

**Comment by thirionjwf** [comment]
Thanks. Much appreciated. You can close the "issue".

**Comment by troch** [comment]
:+1:
