### ISSUE TITLE
angular 4 and bootstrap 3.7 +

### ISSUE THREAD

**Issue by munish29sharma** [troch/angular-multi-step-form#72]
Can i use this for angular 4 with bootstrap 3.7 + ?

**Comment by troch** [comment]
Hi @munish29sharma, this library is Angular 1.x only

**Comment by munish29sharma** [comment]
i need to use stepper in angular 4, could you please suggest something ?

**Comment by troch** [comment]
Nope sorry, I am not using angular 2+, and I'm unfamiliar with its ecosystem.

**Comment by pmullot** [comment]
Have a look at the official Angular Material website : https://material.angular.io/components/stepper/overview
