### ISSUE TITLE
formStepValidity: I am having issues implementing this directive

### ISSUE THREAD

**Issue by JeanHules** [troch/angular-multi-step-form#8]
I have a 4 step form. I would like to use this directive for validating the current step before the user moves onto the next, but am confused on how to properly implement it. 

Do I wrap `<main step-container></main>` in a form or have 4 separate `form` tags for each step within the step template?

I currently have it within each step, but when I `{{$getActiveStep().valid}}` I get a blank and no value is returned.

**Comment by troch** [comment]
Hi @JeanHules 

Form validity refers to the validity of the current step if it contains a form. From within your step, add `formStepValidity` directive in your form, so the multi step form instance can get validity updates:

``` html
<form name="MyForm" form-step-validity>
    ...
</form>
```

and specifies in your list of steps which steps contain a form:

``` javascript
$scope.steps = [
    /* ... */
    {
        controller: 'MyStepController',
        templateUrl: '/form-steps/step-2.html',
        hasForm: true
    }
    /* ... */
];
```

**Comment by JeanHules** [comment]
I was able to figure this out and this code works for me. Tell me if this will break something elsewhere...

```
this.setValidity = function (isValid, stepIndex) {
      var step = this.steps[(stepIndex || this.activeIndex) - 1];
      if (step) {
           step.valid = isValid;
      }
 };
```

change the if statement to:

```
if (step && isValid) {
    step.valid = true;
}
```

Not sure why this works and the original code does not, basically same logic. Let me know what you think.

**Comment by troch** [comment]
That is odd that is not working. `setValidity` should always be called with `isValid`:
- Are you using `form-step-validity` directive or calling `setValidity` directly?
- What version of Angular are you using?

**Comment by troch** [comment]
Inactive so closing this issue. Feel free to re-open.
