### ISSUE TITLE
multiStepFormInstance is not getting injected into controller

### ISSUE THREAD

**Issue by rahul-cuelogic** [troch/angular-multi-step-form#9]
``` javascript
var store_module = angular.module('store', [
    'app.config',
    'flash',
    'multiStepForm'
  ]);


store_module.controller('myStore', ['$scope','multiStepFormInstance', function($scope, multiStepFormInstance){

  $scope.addStore = function() {

    console.log('hello world');
    console.log(multiStepFormInstance.getActiveIndex());
  }
}]);

```

I have a multi step form, in the first step I am asking some user input and before moving to next step I want to do some action with user provided input, first step has 'add store'  button on it's click I am calling the addStore function, here inside this function I want to move  user to next step only if store gets added. For this I require multiStepFormInstance  with which help  I can set activeindex as the desired step index. However  I keep getting following error :

error: [$injector:unpr] Unknown provider: multiStepFormInstanceProvider <- multiStepFormInstance <- myStore

what's the correct way to inject multiStepFormInstance into the controller, am I missing something here?
Is is possible to change step from controller method ?

**Comment by rahul-cuelogic** [comment]
Hi @troch  

Is it possible to change step from controller method ?

**Comment by troch** [comment]
A controller will only receive `multiStepFormInstance` if it is used by a `<multi-step-container steps="..."></multi-step-container>`. So you need to configure your steps with your controller on one of the steps, and let the directive instantiate them (it will provide them the multiStepFormInstance).

> Is it possible to change step from controller method ?

I am not sure to understand your question.

**Comment by rahul-cuelogic** [comment]
Hi @troch 

Here is my code, not sure what I am missing here
my store.html file is as follows in this file I am loading the steps by using the `<multi-step-container>` directive

```

<div class="wrapper-section">
  <div class="container" ng-controller="homeCtrl">

  <multi-step-container steps="storeSteps" on-cancel="$dismiss()" on-finish="$close()" search-id="'step'">

          <main step-container>



          </main>

    </multi-step-container>


  </div>
</div>

```

Here is my app.js file inside which I have defined homeCtrl like this:

```

app.controller('homeCtrl',['$scope', '$http', function($scope, $http) {


    $scope.storeSteps = [
                    {
                        templateUrl: '/app/modules/common-views/store/launch-setup.html',
                        hasForm: true,
                        controller: 'homeCtrl'
                    },
                    {
                        templateUrl: '/app/modules/common-views/store/step-one.html',
                        hasForm: true
                    },
                    {
                        templateUrl: '/app/modules/common-views/store/step-two.html',
                    },
                    {
                        templateUrl: '/app/modules/common-views/store/step-three.html',
                    },
                    {
                        templateUrl: '/app/modules/common-views/store/finish.html',
                    }

                ];

    $scope.addStore = function() {

    console.log('hello world');
    multiStepFormInstance.setActiveIndex(2);
    //console.log(multiStepFormInstance.getActiveIndex());
  }
}]);

```

_Is it possible to change step from controller method ?_

By this I mean on my first step (i.e. launch-setup.html) there is 'Add' button  on click of which I will add a record and want to navigate to next step if the record is successfully added, if not, then show the error message. For this I have written addStore() method inside the controller.
I want to know is it possible to render step 2 from this addStore method defined in controller?

**Comment by troch** [comment]
Your code won't work, I am not sure what you want to do. But 'homeCtrl' cannot be a form step controller as well as the controller defining your steps. So you need two different controllers.

``` javascript
app.controller('stepCtrl', ['$scope', 'multiStepFormInstance', function ($scope, multiStepFormInstance) {
    $scope.addStore = function() {
         console.log('hello world');
         multiStepFormInstance.setActiveIndex(2);
         //console.log(multiStepFormInstance.getActiveIndex());
    };
});

app.controller('homeCtrl',['$scope', '$http', function($scope, $http) {
    $scope.storeSteps = [
                    {
                        templateUrl: '/app/modules/common-views/store/launch-setup.html',
                        hasForm: true,
                        controller: 'stepCtrl'
                    },
                    {
                        templateUrl: '/app/modules/common-views/store/step-one.html',
                        hasForm: true
                    },
                    {
                        templateUrl: '/app/modules/common-views/store/step-two.html',
                    },
                    {
                        templateUrl: '/app/modules/common-views/store/step-three.html',
                    },
                    {
                        templateUrl: '/app/modules/common-views/store/finish.html',
                    }

                ];
  }
}]);
```

**Comment by rahul-cuelogic** [comment]
Hi @troch ,

I created separate controllers as you mentioned in above comment, I am still the getting the same errror

```
Error: [$injector:unpr] Unknown provider: multiStepFormInstanceProvider <- multiStepFormInstance <- stepCtrl
http://errors.angularjs.org/1.4.5/$injector/unpr?p0=multiStepFormInstanceProvider%20%3C-%20multiStepFormInstance%20%3C-%20stepCtrl
```

**Comment by rahul-cuelogic** [comment]
Hi @troch ,
Do you have a sample example of injecting 'multiStepFormInstance' into controller? may be, I could refer that to see it in action and figure out what I am missing here

**Comment by troch** [comment]
I don't have a live example, but just injected it here: http://blog.reactandbethankful.com/angular-multi-step-form/#/saving-data (https://github.com/troch/troch.github.io/blob/master/angular-multi-step-form/scripts/app.js#L143).

Are you certain you don't use 'stepCtrl' anywhere else in your app? The error you see is typical of the controller being instantiated outside the directive.

**Comment by rahul-cuelogic** [comment]
Thank you so much @troch ,

```
Are you certain you don't use 'stepCtrl' anywhere else in your app? The error you see is typical of the controller being instantiated outside the directive.
```

stepCtrl was getting instantiated from ng-controller directive in my HTML, I removed that it is working fine.

Again thanks a lot :+1:
